### ISSUE TITLE
Question about analysis performance of Jodroid

### ISSUE THREAD

**Issue by nuaa040840308** [mohrm/android-analyzer#13]
Hi,
   I have built and run Jodroid successfully. However, I found a question when analyzing an apk (SendSMS.apk).
  I also analyzed the apk using Flowdriod. Compared the results generated by Jodroid and flowdroid, I found that Jodroid cannot find any sensitive flows, but flowdroid can find many sensitive flows.
  The results  are attached. I want to know why?
Here is flowdroid:
![16p9uc hbxdkzewohr9ik](https://cloud.githubusercontent.com/assets/13410137/11468484/d683f8ee-978a-11e5-8c2c-a4ea67851270.jpg)
Here is jodroid:
![jodroid](https://cloud.githubusercontent.com/assets/13410137/11468516/1eb48f20-978b-11e5-9f92-52ad70144552.jpg).

The results and analyzed apk file are sent to your email :martin.mohr@kit.edu.

I want to know why?

**Comment by bnord01** [comment]
There are two possible reasons for this:
1. The flows found by flowdroid are not considered critical as sources and thinks are not declared in the used policy. This is most likely the reason for most flows. By default jodroid uses a very minimalistic policy defined in [assets/policytemplate.json](https://github.com/mohrm/android-analyzer/blob/master/assets/policytemplate.json). If you want to compare results you should make sure to use the same policy for both tools.  
2. The jodroid results are incorrect due to control flow holes because the incomplete life cycle model used by jodroid. UI callbacks and other are currently not handled by jodroid and flowdroid has by now a more complete model for that as far as I know.

**Comment by mohrm** [comment]
I guess I can close this.
